apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foo-pvc
  namespace: demo
spec:
  storageClassName: "local-path" # Empty string must be explicitly set otherwise default StorageClass will be set
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
  # volumeName: foo-pv
